apps/ninico/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^perfil$', views.perfil, name='perfil'),
    url(r'^perfil/feed$', views.feed, name='feed'),
    url(r'^perfil/about$', views.about, name='about'),
    url(r'^perfil/relationship$', views.relationship, name='relationship'),
    url(r'^perfil/communities$', views.communities, name='communities'),
    url(r'^perfil/videos$', views.videos, name='videos'),
    url(r'^perfil/sugestoes$', views.suggestions, name='sugestoes'),
    url(r'^perfil/ver-depois$', views.see_after, name='ver-depois'),
    url(r'^perfil/favoritos$', views.favorites, name='favoritos'),
    url(r'^comunidade$', views.community, name='comunidade'),
    url(r'^comunidade/membros$', views.community_members, name='comunidade-membros'),
    url(r'^comunidade/about$', views.community_about, name='comunidade-sobre'),
    url(r'^comunidade/videos$', views.community_videos, name='comunidade-videos'),
    url(r'^comunidade/perguntas$', views.community_question, name='comunidade-perguntas'),
    url(r'^notificacoes$', views.notifications, name='notificacao'),
    url(r'^notificacoes/membros$', views.member_notifications, name='notificacao-membros'),
    url(r'^notificacoes/perguntas-e-respostas$', views.questions_and_answers_notifications, name='notificacao-perguntas-e-respostas'),
    url(r'^criar-artigo$', views.write_article, name='criar-artigo'),
    url(r'^criar-pergunta$', views.write_question, name='criar-pergunta'),
    url(r'^post$', views.post, name='post'),
    url(r'^question$', views.question, name='question'),
    url(r'^search$', views.search, name='pesquisa'),
    url(r'^categoria$', views.category, name='categoria'),
    url(r'^test_abc$', views.test_abc, name='teste_abc'),
    url(r'^editar-publicacoes$', views.edit_publications, name='editar_publicacoes'),
    url(r'^erro-404$', views.handler404, name='erro_page'),
    url(r'^email/recovery$', views.email_recovery, name='recovery'),
    url(r'^email/register$', views.email_register, name='register'),
    url(r'^email/resend-confirmation$', views.email_resend_confirmation, name='resend-confirmation'),
]

apps/userprofile/urls.py
from django.conf.urls import url

from . import views
from apps.core.views import user as userView

urlpatterns = [

    url(r'^edit/$', views.ProfileEditView.as_view(), name='edit'),

    url(r'^get_state/$', views.ProfileGetState.as_view(), name='get_state'),
    url(r'^get_city/$', views.ProfileGetCity.as_view(), name='get_city'),

    url(r'^occupation/$', views.OccupationManageView.as_view(), name='occupation_manage'),
    url(r'^occupation/add/$', views.OccupationAddView.as_view(), name='occupation_add'),
    url(r'^occupation/(?P<occupation_id>[0-9]+)/$', views.OccupationShowView.as_view(), name='occupation_show'),
    url(r'^occupation/edit/(?P<occupation_id>[0-9]+)/$', views.OccupationEditView.as_view(), name='occupation_edit'),
    url(r'^occupation/delete/(?P<occupation_id>[0-9]+)/$', views.OccupationDeleteView.as_view(), name='occupation_delete'),

    url(r'^feed/$', userView.CoreUserFeed.as_view(), name='user_feed'),
    url(r'^(?P<username>[a-z0-9_-]+)/$', userView.CoreUserProfile.as_view(), name='user_profile'),
    url(r'^search/(?P<username>[a-z0-9_-]+)/$', userView.CoreUserSearch.as_view(), name='search'),
    url(r'^list/(?P<username>[a-z0-9_-]+)/$', userView.CoreUserList.as_view(), name='list'),
    url(r'^list_articles/(?P<username>[a-z0-9_-]+)/$', userView.CoreUserList.as_view(), name='list_articles'),

    url(r'^(?P<username>[a-z0-9_-]+)/$', views.ProfileShowView.as_view(), name='show'),
    url(r'^(?P<username>[a-z0-9_-]+)/followings/$', views.ProfileFollowingsView.as_view(), name='followings'),
    url(r'^(?P<username>[a-z0-9_-]+)/followers/$', views.ProfileFollowersView.as_view(), name='followers'),
    url(r'^(?P<username>[a-z0-9_-]+)/communities/$', views.ProfileCommunitiesView.as_view(), name='communities'),

]

rede_gsti/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import cache_page
from apps.core.views.core import Home, CoreAllRanking
from apps.core.views import search as CoreSearch
from apps.core.views.frontend import FrontEndBase
from django.contrib.sitemaps import views as sitemap_views
from apps.core.sitemap import sitemaps
from rede_gsti.urls_old import urls_old
from django.views.generic import RedirectView

handler400 = "apps.core.views.errors.handler400"
handler403 = "apps.core.views.errors.handler403"
handler404 = "apps.core.views.errors.handler404"
handler500 = "apps.core.views.errors.handler500"

url_statics = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
url_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
url_search_all = [url(r'(?P<params>.*)$', CoreSearch.SearchAll.as_view(), name='search_all')]
url_job_vacancy = url(_(r'^jobs/'), include('apps.job_vacancy.urls', namespace='jobs'))

urlpatterns = [

    url(r'^$', Home.as_view(), name='index'),
    url(r'^ranking/$', CoreAllRanking.as_view(), name='ranking'),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(_(r'^admin/'), include(admin.site.urls)),

    # API
    url(r'^api/v(?P<version>(1.0))/', include('apps.api.urls', namespace='api')),

    # Job vacancy
    url_job_vacancy,

    # Translators: URL root de conta
    url(_(r'^account/'), include('apps.core.urls.account', namespace='account')),

    # Translators: URL root de comentario
    url(_(r'^comment/'), include('apps.comment.urls', namespace='comment')),

    # Translators: URL root de pergunta
    url(_(r'^push/'), include('apps.core.urls.push', namespace='push')),

    # Translators: URL root de perfil de usuario
    url(_(r'^profile/'), include('apps.core.urls.user', namespace='profile')),

    # Translators: URL root de company-organization
    url(_(r'^organization/'), include('apps.core.urls.company', namespace='organization')),

    # Translators: URL de conta social
    url(_(r'^socialaccount/'), include('apps.socialaccount.urls', namespace='socialaccount')),

    # Translators: URL de acoes sociais
    url(_(r'^socialactions/'), include('apps.socialactions.urls', namespace='socialactions')),

    # Translators: URL root de redes sociais
    url('', include('social_django.urls', namespace='social')),

    # Translators: URL root de notificacoes
    url(_(r'^notifications/'), include('apps.core.urls.notifications', namespace='notifications')),

    # Translators: URL root de notificacoes
    url(_(r'^hint/'), include('apps.core.urls.hint', namespace='hint')),

    #FIXED ARTICLES REDIRECTS
    url('2011/02/importancia-das-certificacoes.html', RedirectView.as_view(url="/2011/06/importancia-da-certificacao-em-ti-iso.html", permanent=True)),
    url('2012/10/gerenciamento-de-problemas-em-pequenas.html', RedirectView.as_view(url="/2015/11/gerenciamento-de-problemas-em-pequenas-organizacoes.html", permanent=True)),
    url('2013/09/simulado-cobit5.html', RedirectView.as_view(url="/2009/10/simulado-cobit-foundation-5.html", permanent=True)),
    url('2013/02/itil-computacao-em-nuvem.html', RedirectView.as_view(url="/2011/06/computacao-em-nuvem-e-itil-cloud.html", permanent=True)),
    url('2013/02/cloud-computing-foundation.html', RedirectView.as_view(url="/2014/11/itil-e-cloud-computing-video-1724.html", permanent=True)),
    url(r'2012/09/itil-v3-2011.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "itil-v3-2011", 'year': "2012", 'month': '04'}),
    url(r'2011/07/tcc-monografia-em-itil-2.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "tcc-monografia-em-itil-2", 'year': "2012", 'month': '09'}),
    url(r'2009/09/principais-desafios-da-ti-iii.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "principais-desafios-da-ti-ii", 'year': "2009", 'month': '09'}),
    url(r'2016/10/10-passos-para-elaborar-um-plano-da-capacidade-de-ti.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "10-passos-para-elaborar-um-plano-da-capacidade-de-ti", 'year': "2012", 'month': '08'}),
    url(r'2011/07/simulado-iso-27002-foundation-2.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "simulado-iso-27002", 'year': "2011", 'month': '04'}),

    # Translators: URL root de publicacao
    url(_(r'^'), include('apps.core.urls.article', namespace='article')),

    # Translators: URL root CORE de acoes sociais
    url(_(r'^'), include('apps.core.urls.socialactions', namespace='core_socialactions')),

    # Translators: URL root de categoria
    url(_(r'^category-feed/'), include('apps.core.urls.category', namespace='category')),

    # Translators: URL root de pergunta
    url(_(r'^question/'), include('apps.core.urls.question', namespace='question')),

    # Translators: URL root de contato
    url(_(r'^contact/'), include('apps.core.urls.contact', namespace='contact')),

    # Translators: URL root de contato
    url(_(r'^mailmanager/'), include('apps.mailmanager.urls', namespace='mailmanager')),

    # Translators: URL root de denuncia
    url(_(r'^complaint/'), include('apps.complaint.urls', namespace='complaint')),

    # Translators: URL root de configuracao
    url(_(r'^settings/'), include('apps.core.urls.configuration', namespace='configuration')),


    # Translators: URL root de fe   ed
    url(_(r'^feed/'), include('apps.core.urls.feed', namespace='feed')),

    # Translators: URL root de amp
    url(_(r'^'), include('apps.core.urls.amp', namespace='amp')),

    # Translators: URL root of user alerts
    url(_(r'^useralerts/'), include('apps.useralerts.urls', namespace='useralerts')),

    # Translators: URL de curso
    url(_(r'^courses/'), include('apps.core.urls.course', namespace='course')),

    # Translators: URL de curso
    url(_(r'^rating/'), include('apps.core.urls.rating', namespace='rating')),

    # Translators: URL core adicionais
    url(_(r'^'), include('apps.core.urls.core', namespace='core')),

    url(r'^chaining/', include('smart_selects.urls')),

    # Translators: URL de buscai
    url(_(r'^'), include('apps.core.urls.search', namespace='search')),



    # Translators: URl geography
    url(_(r'^geography/'), include('apps.core.urls.geography', namespace='geography')),


    url(_(r'^superadmin/'), include('apps.core.urls.superuser', namespace='superuser')),

    # Translators: URL root de comunidade
    url(_(r'^'), include('apps.core.urls.community', namespace='community')),

    url(r'^ideia-summernote/', include('apps.core.urls.summernote', namespace='ideia-summernote')),

    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', cache_page(settings.TIME_TO_REFRESH_SITEMAP)(sitemap_views.sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url(r'^', include('apps.core.urls.blogspot', namespace='blogspot')),

] + url_statics + url_media + urls_old
urls_front_end = [
    url(_(r'^front-end/(?P<template>[a-z0-9./]+(?:(-|_)[a-z0-9.]+)*)'), FrontEndBase.as_view())
]

if not (settings.ENVIRONMENT=='production'):
    urlpatterns += urls_front_end

if hasattr(settings, 'PROFILER_APP') and getattr(settings, 'PROFILER_APP') == 'silk' and getattr(settings, 'ENVIRONMENT') == 'develop':
    urlpatterns += [
        url(r'^admin/silk/', include('silk.urls', namespace='silk'))
    ]
# urlpatterns += url_search_all

apps/core/forms/WizardForm.py
from apps.custom_base.service.custom import IdeiaForm, forms
from django.conf import settings
__author__ = 'phillip'

class WizardBase(IdeiaForm):
    step = forms.IntegerField(max_value=settings.WIZARD_STEPS_TOTAL)


class WizardFormStepOne(WizardBase):
    pass

apps/core/forms/wizard.py
# coding=utf-8
from django.db.models import Q
from apps.account.models import User
from apps.account.service.forms import BaseSignupForm
from apps.custom_base.service.custom import IdeiaForm
from apps.geography.models import State, City
from apps.userprofile.models import Responsibility, GenderType
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _
from apps.userprofile.service import business as BusinessUserProfile
from django.core.exceptions import ValidationError
from django.utils import timezone


class WizardForm(IdeiaForm):

    user = None

    def __init__(self, data=None, files=None, user=None, *args, **kwargs):

        self.user = user
        super(WizardForm, self).__init__(data=data, files=files, *args, **kwargs)


class StepOneWizardForm(BaseSignupForm, WizardForm):


    responsibility = forms.ModelChoiceField(queryset=Responsibility.objects.filter(avaiable_to_choose=True), required=False)
    state = forms.ModelChoiceField(queryset=State.objects.filter(country=1), required=False)
    birth = forms.DateField(input_formats=['%d/%m/%Y'], required=True)
    gender = forms.ChoiceField(choices=GenderType.CHOICES, required=True)
    city = forms.ModelChoiceField(queryset=City.objects.all(), required=True)
    profile_picture = forms.ImageField(required=False)
    wizard_step = forms.IntegerField(required=True)

    def clean_email(self):
        return self.user.email if self.user.email else super(StepOneWizardForm, self).clean_email()

    def is_email_valid(self, valid):

        if 'email' in self.cleaned_data and User.objects.filter(Q(email=self.cleaned_data['email']) & ~Q(id=self.user.id)).exists():
            self.add_error('email', ValidationError(_('Email is already in use.'), code='email'))
            valid = False

        return valid

    def __init__(self, data=None, files=None, user=None, *args, **kwargs):

        self.initial = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email
        }

        self.initial.update(kwargs.get('initial', {}))

        if user.email:
            self.declared_fields['email'].required = False

        if user and hasattr(user, 'user_profile'):
            self.initial = self.load_initial_data(user, self.initial)

        kwargs.update({
            'initial': self.initial
        })

        kwargs.update({
            'user': user
        })

        super(StepOneWizardForm, self).__init__(data, files, *args, **kwargs)


    def load_initial_data(self, user, initial):

        if user.user_profile.city:
            initial.update({
                'state': user.user_profile.city.state,
                'city': user.user_profile.city,
            })

        if user.user_profile.birth:
            initial.update({
                'birth': user.user_profile.birth
            })

        if user.user_profile.current_occupation:
            initial.update({
                'responsibility': user.user_profile.current_occupation.responsibility
            })

        if user.user_profile.gender:
            initial.update({
                'gender': user.user_profile.gender
            })

        return initial

    def is_valid(self):

        is_valid = super(StepOneWizardForm, self).is_valid()
        image = self.cleaned_data.get('profile_picture', False)
        birth = self.cleaned_data.get('birth', None)

        # TODO: Remove this POG
        responsibility = self.cleaned_data.get('responsibility', None)
        if not responsibility:
            is_valid = False
            self.add_error('responsibility', ValidationError(u'Este campo é obrigatório', code='responsibility'))

        if birth and birth.year > timezone.now().year:
            is_valid = False
            self.add_error('birth', ValidationError(_('Birth invalid.'), code='birth'))

        if 'gender' in self.cleaned_data:
            if self.cleaned_data['gender'].upper() not in ['M', 'F']:
                is_valid = False
                self.add_error('gender',
                               ValidationError(_('Gênero não permitido.'), code='gender'))

        if image and 'image' in self.changed_data:
            if image.content_type not in getattr(settings, 'IMAGES_ALLOWED'):
                self.add_error('profile_picture',
                               ValidationError(_('Image format is not allowed.'), code='profile_picture'))
                is_valid = False

            if image._size > 1024 * 1024:
                self.add_error('profile_picture',
                               ValidationError(_('Image size more than 1mb.'), code='profile_picture'))
                is_valid = False

        return is_valid

    def __process__(self):

        process_profile = BusinessUserProfile.edit_profile(self.user, self.cleaned_data)
        process_occupation = BusinessUserProfile.update_or_create_occupation(
            process_profile,
            responsibilities=[self.cleaned_data.get('responsibility')])

        return process_profile if (process_profile and process_occupation) else False


class StepTwoWizardForm(WizardForm):

    pass

templates/core/partials/wizard/community-segment.html
{% load social_tags %}
{% load thumbor_tags %}

{% if communities %}

    {% for community in communities %}
    <div class="suggestion">
        <div class="perfil">
            <span>
                <figure>
                    <img width="80" height="80" src="{% thumbor_url community.get_picture.url width=80 height=80 smart=False fit_in=False %}" alt="{{ community.title }}" title="{{ community.title }}">
                </figure>
            </span>
            <div>
                <span class="perfil-name" title="{{ community.title }}">{{ community.title }}</span>
                <span class="perfil-counter">
                  <span class="counter-number">{% followers_count community as followers_count_value %}{{ followers_count_value }}</span> Seguidor{{ followers_count_value|pluralize:'es' }}
                </span>
                {% follow_action community url_next ajax=True %}
            </div>
        </div>
    </div>
    {% endfor %}

    {% if communities and communities.has_next %}
    <div class="col-lg-12 next-button-container">
        <a class="btn-default btn-block btn-wizard-next-categories" data-jscroll-next href="{% url "profile:wizard" step=3 %}?criteria={{ criteria }}&page={{ page }}">Carregar mais comunidades</a>
    </div>
    {% endif %}

{% else %}

    <div class="col-lg-12">
        Nenhuma comunidade encontrada com este critério de busca.
    </div>

{% endif %}

templates/core/partials/wizard/wizard-base.html
{% extends 'home/layout/base.html' %}

{% block title %} Wizard{% endblock %}

{% block content %}

<main class="container main">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="modal-menssage">
                {% block step_message %}
                    <i class="gsticon gsticon-check"></i>
                    <h4 class="message-title">Você agora tem uma conta na <strong>Rede GSTI.</strong></h4>
                    <h5>Adicione uma foto e preencha os campos exigidos abaixo.</h5>
                {% endblock step_message %}
            </div>
            <div class="steps">
                {% block wizard_content %}{% endblock wizard_content %}
            </div>
        </div>
    </div>
</main>
{% endblock content %}

{% block javascripts %}
    {{ block.super }}

    {% include 'inline_scripts/wizard.html' %}

{% endblock %}

templates/core/partials/wizard/wizard-step-numbers.html
 <ul class="step-items">
    <li class="step{% if active == 1 %} active{% endif %}">1</li>
    <li class="step{% if active == 2 %} active{% endif %}">2</li>
    <li class="step{% if active == 3 %} active{% endif %}">3</li>
</ul>

templates/core/partials/wizard/wizard-step-one.html
{% extends 'core/partials/wizard/wizard-base.html' %}
{% load i18n %}
{% load thumbor_tags %}
{% load widget_tweaks %}
{% block wizard_content %}

    <form id="form-personal-info" action="{% url 'profile:wizard' step %}" method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.non_field_errors.as_list }}

        <div class="steps-container row">
            <div class="col-lg-12"><hr></div>
            <div class="col-lg-4">
                <div class="custom-file-upload set-avatar"
                     data-module="dropzoneUploader"
                     data-original-image="{% if form.profile_picture %}{{ form.profile_picture.value.url }}{% elif request.user.user_profile %}{{ request.user.user_profile.profile_picture.url }}{% endif %}">
                    <div class="custom-file-content">
                        <i class="gsticon gsticon-cloud-upload"></i>
                        <h5><strong>Foto de perfil</strong></h5>
                        <p>Arraste a imagem para este campo ou <a href="javascript:;" data-trigger="file">clique aqui</a></p>
                    </div>
                    <input type="file" accept="image/*" name="{{ form.profile_picture.name }}">
                    <div class="custom-file-upload-result" data-content="file"></div>
                    <span class="help-block">
                        {% if form.profile_picture.errors %}  {{ form.profile_picture.errors }} {% endif %}
                    </span>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="row">
                    <div class="clearfix">
                        <div data-form-group class="col-lg-12 item-form">
                            {% render_field form.responsibility id="responsibility" data-toggle="selectize" data-module="profession" placeholder="Área de atuação" %}
                            <span class="help-block">
                                Área de atuação <br>
                                {% if form.responsibility.errors %}  {{ form.responsibility.errors }} {% endif %}
                            </span>
                        </div>
                    </div>

                <div class="clearfix">
                    <div class="col-lg-5 item-form {% if form.first_name.errors %}has-error{% endif %}">
                          {% trans "First name" as first_name_placeholder %}
                          {% render_field form.first_name class="form-control" placeholder=first_name_placeholder %}

                          <span class="help-block">
                            Primeiro nome <br>
                            {% if form.first_name.errors %}  {{ form.first_name.errors }} {% endif %}
                          </span>
                        </div>
                        <div class="col-lg-7 item-form {% if form.last_name.errors %}has-error{% endif %}">
                        {% trans "Last Name" as last_name_placeholder %}
                          {% render_field form.last_name class="form-control" placeholder=last_name_placeholder %}

                          <span class="help-block">
                            Último nome <br>
                            {% if form.last_name.errors %}  {{ form.last_name.errors }} {% endif %}
                          </span>
                        </div>
                </div>
                {% if not request.user.email %}
                    <div class="clearfix">
                     <div class="col-lg-12 item-form {% if form.email.errors %}has-error{% endif %}">
                         {% render_field form.email class="form-control" type="email" maxlength="150" %}
                          <span class="help-block">
                            Email <br>
                            {% if form.email.errors %}  {{ form.email.errors }} {% endif %}
                          </span>
                        </div>

                </div>

                {% endif %}



                    <div class="clearfix">
                        <div data-form-group class="col-lg-6 item-form">
                            <div class="custom-calendar">
                                {% render_field form.birth class="datetime-picker" id="birth" placeholder="Aniversário" autocomplete="off" %}
                                <i class="gsticon gsticon-calendar"></i>
                            </div>
                            <span class="help-block">
                                Data de nascimento
                                {% if form.birth.errors %}  {{ form.birth.errors }} {% endif %}
                            </span>
                        </div>

                        <div data-form-group class="col-lg-6 item-form">

                            <select name="{{ form.gender.name }}" id="{{ form.gender.name }}" class="form-control">
                                <option value="">Sexo</option>
                                {% for value, name in form.fields.gender.choices %}
                                    <option value="{{ value }}" {% if value == form.gender.value %}selected{% endif %}>{{ name|lower|capfirst }}</option>
                                {% endfor %}
                            </select>

                            <span class="help-block">
                              Sexo <br>
                                {% if form.gender.errors %}  {{ form.gender.errors }} {% endif %}
                            </span>
                        </div>
                    </div>
                    <div class="clearfix">
                        <div data-form-group class="col-lg-6 item-form">
                            {% url 'profile:get_city' as profile_get_city %}
                            {% render_field form.state id="state" data-ajax-change="true" data-url=profile_get_city data-target="#city" %}
                            <span class="help-block">
                              Estado onde mora <br>
                                {% if form.state.errors %}  {{ form.state.errors }} {% endif %}
                            </span>
                        </div>
                        <div data-form-group class="col-lg-6 item-form">

                                <select name="city" id="city">
                                    <option value="0" {% if not wizard_profile.city.id %}selected{% endif %} disabled>Cidade</option>
                                    {% for city in cities %}
                                        <option value="{{ city.id }}" {% if request.user.userprofile.city.id == city.id %}selected{% endif %}>{{ city.name }}</option>
                                    {% endfor %}
                                </select>
                            <span class="help-block">
                              Cidade onde mora <br>
                                {% if form.city.errors %}  {{ form.city.errors }} {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row text-right">
            <div class="col-lg-12">
                <hr>
                <button class="btn-green" type="submit">Avançar</button>
            </div>
        </div>
    </form>

{% endblock wizard_content %}

{% block javascripts %}

    {{ block.super }}

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.min.js"></script>
    <script>
        $('.datetime-picker').mask("00/00/0000", {placeholder: "__/__/____"});
    </script>

{% endblock %}

templates/core/partials/wizard/wizard-step-three.html
{% extends 'core/partials/wizard/wizard-base.html' %}

{% load thumbor_tags %}
{%  load comment_tags %}
{% block wizard_content %}
 <div class="modal-menssage">
        <h4 class="message-title">Escolha comunidades de sua preferência</h4>
    </div>
    <div class="steps">
        <ul class="step-items list-inline text-center">
            <li class="step active">1</li>
            <li class="step active">2</li>
            <li class="step active">3</li>
        </ul>
        <hr />
        <form id="form-filter-communities" action="{% url "profile:wizard" step=3 %}" method="GET">
            <div class="form-group">
                <input type="text" class="form-control" data-xhr-input="true" name="criteria" placeholder="Procure comunidades" >
            </div>
            <div id="filter-taxonomies-wizard"></div>
        </form>
        <form id="form-suggestions" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <hr>
            <div class="steps-container">
                <div class="row container-wizard-communities" data-toggle="custom-scroll">
                  {% include 'core/partials/wizard/community-segment.html' %}
                </div>
                <hr>
                <div class="clearfix text-right">
                    <button class="btn-green" type="submit">Concluir</button>
                </div>
            </div>
        </form>
    </div>

{% endblock wizard_content %}

templates/core/partials/wizard/wizard-step-two.html
{% extends 'core/partials/wizard/wizard-base.html' %}

{% load thumbor_tags %}
{% load comment_tags %}
{% block wizard_content %}
    <ul class="step-items list-inline text-center">
        <li class="step active">1</li>
        <li class="step active">2</li>
        <li class="step">3</li>
    </ul>
    <div class="modal-menssage">
        <h4 class="message-title">Escolha categorias de sua preferência</h4>
    </div>
    <div class="steps">
        <form id="form-filter-categories" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <hr>
            <div class="steps-container row">
                <div class="col-lg-12">
                    <div class="row">
                        {% if categories %}
                            {% for category in categories %}
                                <div class="modal-category">
                                    <label class="modal-category-label">
                                        <span class="modal-category-check">
                                            <input type="checkbox" name="taxonomies" id="category-{{ category.id }}" value="{{ category.id }}">
                                        </span>
                                        <span class="color-governance">{{ category.description }}</span>
                                    </label>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="item-form"></div>
                    <hr>
                </div>
                <div class="col-lg-offset-4 col-lg-8 text-right">
{#                    <a href="{% url "profile:wizard" 1 %}" class="btn-default">voltar</a>#}
                    <button data-clean-action="true" class="btn-green" type="submit">Avançar</button>
                </div>
            </div>
        </form>
    </div>

{% endblock wizard_content %}

templates/core/partials/wizard/wizard-success.html
{% extends 'home/layout/base.html' %}

{% block title %} Wizard{% endblock %}

{% load i18n %}

{% block content %}
    <main class="container main">
        <div class="success-page">
            <h2 class="success-page-title">Bem vindo ao Portal GSTI</h2>
            <h4 class="success-page-subtitle">Estamos felizes com a sua chegada.</h4>
            <p class="success-page-description"></p>
            <a href="{% url 'profile:feed' %}" class="btn-grey success-page-btn">Ver meu feed</a>
        </div>
    </main>
{% endblock %}