apps/account/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^signup/$', views.RegisterView.as_view(), name='signup'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/', views.LogoutView.as_view(), name='logout'),
    url(r'^is-logged/', views.IsLogged.as_view(), name='is_logged'),

    url(r'^change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^forgot_password/$', views.ForgotPasswordView.as_view(), name='forgot_password'),
    url(r'^registered-successfully/$', views.RegisteredSuccessView.as_view(), name='registered_successfully'),
    url(r'^mail_validation/(?P<activation_key>[0-9a-z]{40})/$', views.MailValidationView.as_view(), name='mail_validation'),
    url(r'^recovery_password/(?P<activation_key>[0-9a-z]{40})/$', views.RecoveryValidationView.as_view(), name='recovery_password'),
    url(r'^recovery_validation/(?P<activation_key>[0-9a-z]{40})/$', views.RecoveryValidationView.as_view(), name='recovery_validation'),
    url(r'^resend_account_confirmation$', views.ResendAccountConfirmationView.as_view(), name='resend_account_confirmation'),

]

apps/comment/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views

urlpatterns = [

    # Translators: URL de pagina de salvar comentario
    url(_(r'^save/$'), views.CommentSaveView.as_view(), name='save'),

    # Translators: URL de pagina de salvar resposta
    url(_(r'^answer-save/$'), views.CommentSaveAnswer.as_view(), name='answer-save'),

    # Translators: URL de pagina de edicao de comentarios
    url(_(r'^edit/$'), views.CommentUpdateView.as_view(), name='edit'),

    # Translators: URL de pagina de edicao de resposta
    url(_(r'^edit-answer/$'), views.CommentUpdateAnswerView.as_view(), name='edit-answer'),

    # Translators: URL de pagina de listagem de respostas
    url(_(r'^list-answer/$'), views.CommentAnswerList.as_view(), name='list-answer'),

    # Translators: URL de pagina atualizacao de comentarios
    url(_(r'^update/$'), views.CommentUpdateView.as_view(), name='update'),

    # Translators: URL de pagina de listagem de comentarios
    url(_(r'^list/$'), views.CommentList.as_view(), name='list'),

    # Translators: URL de pagina de delete de comentario
    url(_(r'^delete$'), views.CommentDeleteView.as_view(), name='delete'),

    # Translators: URL de pagina de contagem de comentario
    url(_(r'^count/(?P<object_to_link>\d+)/(?P<content_type>[a-z]+)$'), views.CommentCountView.as_view(), name='count')
]

apps/complaint/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views

urlpatterns = [

    # url(r'^(?P<complaint>\w{0,50})/$', views.ComplaintView.as_view(), name='report')
    # Translators: URL de denunciar objeto
    url(_(r'^(?P<object_type>[a-z]+)/(?P<object_id>[0-9]+)$'), views.ComplaintView.as_view(), name='report')

]

apps/socialactions/urls.py
__author__ = 'phillip'

from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from . import views

urlpatterns = [

    # Translators: URL de acao social
    url(_(r'^act/(?P<object_to_link>[0-9]+)/(?P<content>[a-zA-Z]+)/(?P<action>[a-z0-9]+(?:-[a-z0-9]+)*)'), views.SocialActionView.as_view(), name='act'),

    # Translators: URL de acao social ajax
    url(_(r'^act/xhr/(?P<object_to_link>[0-9]+)/(?P<content>[a-zA-Z]+)/(?P<action>[a-z0-9]+(?:-[a-z0-9]+)*)'), views.SocialActXHR.as_view(), name='act-xhr'),

    # Translators: URL para saber se o usuario agiu sobre um determinado item
    url(_(r'^acted/(?P<object_to_link>[0-9]+)/(?P<content>[a-zA-Z]+)/(?P<action>[a-z0-9]+(?:-[a-z0-9]+)*)'), views.SocialUserActed.as_view(), name='acted'),

    # Translators: URL de acao social ajax
    url(_(r'^act/ajax/(?P<object_to_link>[0-9]+)/(?P<content>[a-zA-Z]+)/(?P<action>[a-zA-Z]+)'), views.SocialActionAjax.as_view(), name='act-ajax'),

    # Translators: URL de sugerir
    url(_(r'^act/suggest/(?P<object_to_link>[0-9]+)/(?P<content>[a-z]+)/$'), views.SocialActionSuggestArticleToUser.as_view(), name='act-suggest'),

    # Translators: URL de seguidores
    url(_(r'^followers/(?P<content_type_id>[0-9]+)/(?P<object_filter_id>[0-9]+)/$'), views.SocialActionFollowersViews.as_view(), name='get_followers'),

    # Translators: URL de seguindo
    url(_(r'^followings/(?P<content_type_id>[0-9]+)/(?P<object_filter_id>[0-9]+)/$'), views.SocialActionFollowingsViews.as_view(), name='get_followings'),

]

apps/userprofile/urls.py
from django.conf.urls import url

from . import views
from apps.core.views import user as userView

urlpatterns = [

    url(r'^edit/$', views.ProfileEditView.as_view(), name='edit'),

    url(r'^get_state/$', views.ProfileGetState.as_view(), name='get_state'),
    url(r'^get_city/$', views.ProfileGetCity.as_view(), name='get_city'),

    url(r'^occupation/$', views.OccupationManageView.as_view(), name='occupation_manage'),
    url(r'^occupation/add/$', views.OccupationAddView.as_view(), name='occupation_add'),
    url(r'^occupation/(?P<occupation_id>[0-9]+)/$', views.OccupationShowView.as_view(), name='occupation_show'),
    url(r'^occupation/edit/(?P<occupation_id>[0-9]+)/$', views.OccupationEditView.as_view(), name='occupation_edit'),
    url(r'^occupation/delete/(?P<occupation_id>[0-9]+)/$', views.OccupationDeleteView.as_view(), name='occupation_delete'),

    url(r'^feed/$', userView.CoreUserFeed.as_view(), name='user_feed'),
    url(r'^(?P<username>[a-z0-9_-]+)/$', userView.CoreUserProfile.as_view(), name='user_profile'),
    url(r'^search/(?P<username>[a-z0-9_-]+)/$', userView.CoreUserSearch.as_view(), name='search'),
    url(r'^list/(?P<username>[a-z0-9_-]+)/$', userView.CoreUserList.as_view(), name='list'),
    url(r'^list_articles/(?P<username>[a-z0-9_-]+)/$', userView.CoreUserList.as_view(), name='list_articles'),

    url(r'^(?P<username>[a-z0-9_-]+)/$', views.ProfileShowView.as_view(), name='show'),
    url(r'^(?P<username>[a-z0-9_-]+)/followings/$', views.ProfileFollowingsView.as_view(), name='followings'),
    url(r'^(?P<username>[a-z0-9_-]+)/followers/$', views.ProfileFollowersView.as_view(), name='followers'),
    url(r'^(?P<username>[a-z0-9_-]+)/communities/$', views.ProfileCommunitiesView.as_view(), name='communities'),

]

rede_gsti/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import cache_page
from apps.core.views.core import Home, CoreAllRanking
from apps.core.views import search as CoreSearch
from apps.core.views.frontend import FrontEndBase
from django.contrib.sitemaps import views as sitemap_views
from apps.core.sitemap import sitemaps
from rede_gsti.urls_old import urls_old
from django.views.generic import RedirectView

handler400 = "apps.core.views.errors.handler400"
handler403 = "apps.core.views.errors.handler403"
handler404 = "apps.core.views.errors.handler404"
handler500 = "apps.core.views.errors.handler500"

url_statics = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
url_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
url_search_all = [url(r'(?P<params>.*)$', CoreSearch.SearchAll.as_view(), name='search_all')]
url_job_vacancy = url(_(r'^jobs/'), include('apps.job_vacancy.urls', namespace='jobs'))

urlpatterns = [

    url(r'^$', Home.as_view(), name='index'),
    url(r'^ranking/$', CoreAllRanking.as_view(), name='ranking'),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(_(r'^admin/'), include(admin.site.urls)),

    # API
    url(r'^api/v(?P<version>(1.0))/', include('apps.api.urls', namespace='api')),

    # Job vacancy
    url_job_vacancy,

    # Translators: URL root de conta
    url(_(r'^account/'), include('apps.core.urls.account', namespace='account')),

    # Translators: URL root de comentario
    url(_(r'^comment/'), include('apps.comment.urls', namespace='comment')),

    # Translators: URL root de pergunta
    url(_(r'^push/'), include('apps.core.urls.push', namespace='push')),

    # Translators: URL root de perfil de usuario
    url(_(r'^profile/'), include('apps.core.urls.user', namespace='profile')),

    # Translators: URL root de company-organization
    url(_(r'^organization/'), include('apps.core.urls.company', namespace='organization')),

    # Translators: URL de conta social
    url(_(r'^socialaccount/'), include('apps.socialaccount.urls', namespace='socialaccount')),

    # Translators: URL de acoes sociais
    url(_(r'^socialactions/'), include('apps.socialactions.urls', namespace='socialactions')),

    # Translators: URL root de redes sociais
    url('', include('social_django.urls', namespace='social')),

    # Translators: URL root de notificacoes
    url(_(r'^notifications/'), include('apps.core.urls.notifications', namespace='notifications')),

    # Translators: URL root de notificacoes
    url(_(r'^hint/'), include('apps.core.urls.hint', namespace='hint')),

    #FIXED ARTICLES REDIRECTS
    url('2011/02/importancia-das-certificacoes.html', RedirectView.as_view(url="/2011/06/importancia-da-certificacao-em-ti-iso.html", permanent=True)),
    url('2012/10/gerenciamento-de-problemas-em-pequenas.html', RedirectView.as_view(url="/2015/11/gerenciamento-de-problemas-em-pequenas-organizacoes.html", permanent=True)),
    url('2013/09/simulado-cobit5.html', RedirectView.as_view(url="/2009/10/simulado-cobit-foundation-5.html", permanent=True)),
    url('2013/02/itil-computacao-em-nuvem.html', RedirectView.as_view(url="/2011/06/computacao-em-nuvem-e-itil-cloud.html", permanent=True)),
    url('2013/02/cloud-computing-foundation.html', RedirectView.as_view(url="/2014/11/itil-e-cloud-computing-video-1724.html", permanent=True)),
    url(r'2012/09/itil-v3-2011.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "itil-v3-2011", 'year': "2012", 'month': '04'}),
    url(r'2011/07/tcc-monografia-em-itil-2.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "tcc-monografia-em-itil-2", 'year': "2012", 'month': '09'}),
    url(r'2009/09/principais-desafios-da-ti-iii.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "principais-desafios-da-ti-ii", 'year': "2009", 'month': '09'}),
    url(r'2016/10/10-passos-para-elaborar-um-plano-da-capacidade-de-ti.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "10-passos-para-elaborar-um-plano-da-capacidade-de-ti", 'year': "2012", 'month': '08'}),
    url(r'2011/07/simulado-iso-27002-foundation-2.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "simulado-iso-27002", 'year': "2011", 'month': '04'}),

    # Translators: URL root de publicacao
    url(_(r'^'), include('apps.core.urls.article', namespace='article')),

    # Translators: URL root CORE de acoes sociais
    url(_(r'^'), include('apps.core.urls.socialactions', namespace='core_socialactions')),

    # Translators: URL root de categoria
    url(_(r'^category-feed/'), include('apps.core.urls.category', namespace='category')),

    # Translators: URL root de pergunta
    url(_(r'^question/'), include('apps.core.urls.question', namespace='question')),

    # Translators: URL root de contato
    url(_(r'^contact/'), include('apps.core.urls.contact', namespace='contact')),

    # Translators: URL root de contato
    url(_(r'^mailmanager/'), include('apps.mailmanager.urls', namespace='mailmanager')),

    # Translators: URL root de denuncia
    url(_(r'^complaint/'), include('apps.complaint.urls', namespace='complaint')),

    # Translators: URL root de configuracao
    url(_(r'^settings/'), include('apps.core.urls.configuration', namespace='configuration')),


    # Translators: URL root de fe   ed
    url(_(r'^feed/'), include('apps.core.urls.feed', namespace='feed')),

    # Translators: URL root de amp
    url(_(r'^'), include('apps.core.urls.amp', namespace='amp')),

    # Translators: URL root of user alerts
    url(_(r'^useralerts/'), include('apps.useralerts.urls', namespace='useralerts')),

    # Translators: URL de curso
    url(_(r'^courses/'), include('apps.core.urls.course', namespace='course')),

    # Translators: URL de curso
    url(_(r'^rating/'), include('apps.core.urls.rating', namespace='rating')),

    # Translators: URL core adicionais
    url(_(r'^'), include('apps.core.urls.core', namespace='core')),

    url(r'^chaining/', include('smart_selects.urls')),

    # Translators: URL de buscai
    url(_(r'^'), include('apps.core.urls.search', namespace='search')),



    # Translators: URl geography
    url(_(r'^geography/'), include('apps.core.urls.geography', namespace='geography')),


    url(_(r'^superadmin/'), include('apps.core.urls.superuser', namespace='superuser')),

    # Translators: URL root de comunidade
    url(_(r'^'), include('apps.core.urls.community', namespace='community')),

    url(r'^ideia-summernote/', include('apps.core.urls.summernote', namespace='ideia-summernote')),

    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', cache_page(settings.TIME_TO_REFRESH_SITEMAP)(sitemap_views.sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url(r'^', include('apps.core.urls.blogspot', namespace='blogspot')),

] + url_statics + url_media + urls_old
urls_front_end = [
    url(_(r'^front-end/(?P<template>[a-z0-9./]+(?:(-|_)[a-z0-9.]+)*)'), FrontEndBase.as_view())
]

if not (settings.ENVIRONMENT=='production'):
    urlpatterns += urls_front_end

if hasattr(settings, 'PROFILER_APP') and getattr(settings, 'PROFILER_APP') == 'silk' and getattr(settings, 'ENVIRONMENT') == 'develop':
    urlpatterns += [
        url(r'^admin/silk/', include('silk.urls', namespace='silk'))
    ]
# urlpatterns += url_search_all

templates/userprofile/partials/article-segment.html
{% load humanize %}
{% load social_tags %}
{% load avatar_tags %}
{% load thumbor_tags %}
{% load taxonomy_tags %}

<article class="post" itemscope itemtype="http://schema.org/BlogPosting">
    <header class="post-header">
        <span class="post-creator">
            <a class="post-creator-image" href="{% if  instance.author.is_active %}{% url 'profile:show' instance.author.get_username %}{% else %}javascript:;{% endif %}">
                <img src="{% get_avatar instance.author width=40 height=40 smart=False fit_in=False %}" alt="foto de {{ instance.author.get_full_name }}">
                {% if instance.author.profile.contributor %}
                    <div class="is-official" data-toggle="tooltip" data-placement="bottom" title="Equipe do Portal GSTI"></div>
                {% endif%}
            </a>
            <span class="post-creator-userinfo">
                <a class="post-creator-username" href="{% if  instance.author.is_active %}{% url 'profile:show' instance.author.get_username %}{% else %}javascript:;{% endif %}">{{instance.author.get_full_name}}</a>
                <time datetime="{{ instance.publishin|date:'d/m/Y G:i' }}">{{ instance.publishin|naturaltime }}</time>
            </span>
        </span>
        <div class="post-info">
            <a class="post-actions" href="javascript:;" data-toggle="dropdown">
                <i class="gsticon gsticon-ellipsis-v" aria-hidden="true"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <ul class="perfil-actions">
                    {% if instance.author == request.user or perms.article.change_other_articles %}
                        <li><a href="{% url 'article:edit' instance.id %}"><i class="gsticon gsticon-edit"></i> Editar publicação</a></li>
                    {% endif %}
                    <li><a data-url-login="{% url 'account:is_logged' %}" data-trigger="login" data-token="{{ csrf_token }}" href="javascript:;" data-suggest-modal="true" data-content="article" data-object="{{ instance.id }}" data-url="{% url 'socialactions:act-suggest' instance.id 'article' %}"><i class="gsticon gsticon-paper-plane"></i> Sugerir leitura</a></li>
                    <li><a data-url-login="{% url 'account:is_logged' %}" data-trigger="login" data-token="{{ csrf_token }}" data-action="see-later" data-action-type="text" data-action-text="Ver depois" data-action-text-alt="Marcar como visto" data-object="see-later-{{ instance.id }}" data-url-check="{% url 'socialactions:acted' instance.id 'article' 'see-later' %}" href="{% url 'socialactions:act-xhr' instance.id 'article' 'see-later' %}?url_next={{ request.path|urlencode }}"><i class="gsticon gsticon-eye"></i> <span>{{" Ver depois"}}</span></a></li>
                  <li><a data-url-login="{% url 'account:is_logged' %}" data-trigger="login" data-token="{{ csrf_token }}" data-action="favourite" data-action-type="text" data-action-text="Favoritar" data-action-text-alt="Desfavoritar" data-object="favourite-{{ instance.id }}" data-article="{{ instance.id }}" data-url-check="{% url 'socialactions:acted' instance.id 'article' 'favourite' %}" href="{% url 'socialactions:act-xhr' instance.id 'article' 'favourite' %}?url_next={{ request.path|urlencode }}"><i class="gsticon gsticon-star"></i> <span>{{" Favoritar"}}</span></a></li>
                    <li><a data-url-login="{% url 'account:is_logged' %}" data-trigger="login" data-token="{{ csrf_token }}" href="{% url 'complaint:report' 'article' instance.id %}" data-report="true" data-async-module="click" data-async-target="#modal-report" data-async-method="get"><i class="gsticon gsticon-flag"></i> Denunciar</a></li>
                </ul>
            </div>
        </div>

    </header>

    <a class="post-content" href="{% url 'article:view' instance.year instance.month instance.slug %}" itemprop="articleBody">
        {% if instance.get_image %}
            <figure class="{% if instance.image_size.width > 171 %}post-content-thumb{% endif %}">
                <img class="img-responsive" src="{% thumbor_url instance.get_image.url width=instance.image_size.width height=instance.image_size.height smart=False fit_in=False %}" alt="{{ instance.title }}">
            </figure>
        {% endif %}
        <div class="post-text">
            <h3 class="post-title" itemprop="headline">{% if instance.title|length > 67 %}
                {{ instance.title|slice:":67" }}...
            {% else %}
                {{ instance.title }}
            {% endif %}</h3>
            <p>
            {% if instance.get_image %}
                {{ instance.text|safe|striptags|slice:":90"}}{% if instance.text|length >= 90 %}...{% endif %}
            {% else %}
                {{ instance.text|safe|striptags|slice:":250"}}{% if instance.text|length >= 250 %}...{% endif %}
            {% endif %}
            </p>
        </div>
    </a>

    {% if feed.communities.all %}
    <nav class="post-nav">
        <ul class="post-nav-list">{% for community in feed.communities.all %}

            <li><a href="{% url 'community:show' community.slug %}" class="link-to-community">{{ community.taxonomy.description }}</a></li>

        {% endfor %}</ul>
    </nav>
    {% endif %}

    <footer class="post-footer">
        <div class="post-count">{% like_box instance request.path "inline" %}</div>
        <a href="{% url 'article:view' instance.year instance.month instance.slug %}#comments" class="post-count-comments">
            <span id="load-count-comment-{{ feed.content_type.model }}-{{ instance.id }}"
            data-load-async="true" data-load-async-url="{% url 'comment:count' instance.id "article" %}"
            data-load-async-method="get" data-load-async-response-type="json">
                {% csrf_token %}
                <!-- <i class="gsticon gsticon-comment"></i> -->
                <span class="post-count-comments-icon"></span>
                <strong class="load-async load-async-content">0</strong>
            </span>
            <span class="hidden-xs visible-lg-inline">Comentário(s)</span>
        </a>
        <div class="post-share">
            <span data-toggle="dropdown">
                <i class="gsticon gsticon-share-alt"></i>
                <span class="hidden-xs visible-lg-inline">Compartilhar</span>
            </span>
            <div class="dropdown-menu dropdown-menu-right">
                {% with instance_full_url="https://www.portalgsti.com.br"|add:instance.get_absolute_url title=instance.title %}
                    {% include 'article/partials/share.html' with title=instance.title url=instance_full_url %}
                {% endwith %}

            </div>
        </div>
    </footer>

</article>

templates/userprofile/partials/followers-segment.html
{% load social_tags %}
{% load avatar_tags %}
{% load thumbor_tags %}
{% load var_tags %}
{% load i18n %}
{% set counter_content_type = "user" %}

{% if items.object_list %}
    {% for follower in items %}
        {% followers_count follower.author as followers_count_value %}
        <div class="box-perfil">
            <div class="perfil">
                <a href="{% url 'profile:show' follower.author.username %}">
                  <figure>
                    <img src="{% get_avatar follower.author width=90 height=90 smart=False fit_in=False %}" alt="{{ follower.author.get_full_name }}">
                  </figure>
                </a>
                <div>
                    <a class="perfil-name" title="{{ follower.author.get_full_name }}" href="{% if  follower.author.is_active %}{% url 'profile:show' follower.author.get_username %}{% else %}javascript:;{% endif %}">
                        {{ follower.author.get_full_name }}
                    </a>
                    <span class="perfil-counter" data-counter="{{ followers_count_value }}"
                    data-refresh-counter="follow-{{ counter_content_type }}-{{ follower.author.id }}">
                        <span class="counter-number">{{ followers_count_value }}</span>
                        Seguidor{{ followers_count_value|pluralize:'es' }}
                    </span>
                    {% follow_action follower.author url_next %}
                </div>
            </div>
        </div>

    {% endfor %}
    {% if items.has_next %}
        <a data-jscroll-next href="{% url 'profile:followers-search-list' profile.user.username %}?criteria={{ form.cleaned_data.criteria|urlencode }}&page={{ page }}&next={{ url_next|urlencode }}">next</a>
    {% endif %}

{% else %}
    <p class="text-center text-italic">{% trans 'Não existem itens a serem exibidos' %}</p>
    <hr>
{% endif %}

templates/userprofile/partials/profile-card-community.html
{% load thumbor_tags %}
{% load social_tags %}
{% load var_tags %}
{% set counter_content_type = "community" %}

<div class="app-card app-card-profile {{ class_name }}">
    <div class="app-card-content">
        <figure>
            <img src="{% thumbor_url community_obj.get_picture.url width=100 height=100 smart=False fit_in=False %}" alt="{{ community_obj.title }}"
                title="{{ community_obj.title }}">
        </figure>
        <a class="app-card-profile-name {{ class_name }}" title="{{ community_obj.title }}" href="{% url 'community:show' community_obj.slug %}">
            {{ community_obj.title }}
        </a>
        <span class="app-card-profile-followers" data-counter="{{ community_obj.followers }}" data-refresh-counter="follow-{{ counter_content_type }}-{{ community_obj.id }}">
            <span class="app-card-profile-followers-number">{{ community_obj.followers }}</span> Seguidor{{ community_obj.followers|pluralize:'es' }}
        </span>
        {% follow_action community_obj url_next %}
    </div>
</div>

templates/userprofile/partials/profile-edit-item-menu.html
<div class="col-lg-4 text-right">
    <a class="btn btn-perfil {% if item_context == "posts" %}active{% endif %}" href="{% url 'profile:edit-posts' %}">Publicações</a>
    <a class="btn btn-perfil {% if item_context == "questions" %}active{% endif %}" href="{% url 'profile:edit-questions' %}">Perguntas</a>
</div>

templates/userprofile/partials/profilestatus-segment.html
{% load humanize %}
{% load social_tags %}
{% load avatar_tags %}
{% load thumbor_tags %}
{% load taxonomy_tags %}

<div class="post">
    <header class="post-header">
        <div class="post-creator">
            <a class="post-creator-image" href="{% if  instance.author.is_active %}{% url 'profile:show' instance.author.username %}{% else %}javascript:;{% endif %}">
                <img src="{% get_avatar instance.author width=40 height=40 smart=False fit_in=False %}" alt="foto de {{ instance.author.get_full_name }}">
                {% if instance.author.profile.contributor %}
                    <div class="is-official" data-toggle="tooltip" data-placement="bottom" title="Equipe do Portal GSTI"></div>
                {% endif%}
            </a>
            <span class="post-creator-userinfo">
                <a class="post-creator-username" href="{% if  instance.author.is_active %}{% url 'profile:show' instance.author.get_username %}{% else %}javascript:;{% endif %}">{{instance.author.get_full_name}}</a>
                <time datetime="{{ instance.publishin|date:'d/m/Y G:i' }}">{{ instance.publishin|naturaltime }}</time>
            </span>
        </div>
        <div class="post-info">
            <a class="post-actions" href="javascript:;" data-toggle="dropdown">
                <i class="gsticon gsticon-ellipsis-v" aria-hidden="true"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <ul class="perfil-actions">
                    {% if instance.author == request.user %}
                    <li>
                        <a href="#modal-delete-status" data-delete-url="{% url 'profile:delete_profilestatus' instance.id %}" data-toggle="modal">
                            <i class="gsticon gsticon-trash-o"></i> Remover
                        </a>
                    </li>
                     {% endif %}
                    <li><a data-url-login="{% url 'account:is_logged' %}" data-trigger="login" data-token="{{ csrf_token }}" href="{% url 'complaint:report' 'profilestatus' instance.id %}" data-report="true" data-async-module="click" data-async-target="#modal-report" data-async-method="get"><i class="gsticon gsticon-flag"></i> Denunciar</a></li>

                </ul>
            </div>
        </div>
    </header>
    <a class="post-content" href="{{ instance.get_absolute_url }}">
        <div class="post-text">
            <h3 class="post-title">{{ instance.text }}</h3>
        </div>
    </a>
    <footer class="post-footer">
        <div class="post-count">{% like_box instance request.path "inline" %}</div>
        <a href="{{ instance.get_absolute_url }}#comments" class="post-count-comments">
            <span id="load-count-comment-{{ feed.content_type.model }}-{{ instance.id }}"
            data-load-async="true" data-load-async-url="{% url 'comment:count' instance.id "profilestatus" %}"
            data-load-async-method="get" data-load-async-response-type="json">
                {% csrf_token %}
                <span class="post-count-comments-icon"></span>
                <strong class="load-async load-async-content">{{ instance.comment_count|default_if_none:0 }}</strong>
            </span>
            <span class="hidden-xs visible-lg-inline">Comentário(s)</span>
        </a>
        <div class="post-share">
            <span data-toggle="dropdown">
                <i class="gsticon gsticon-share-alt"></i>
                <span class="hidden-xs visible-lg-inline">Compartilhar</span>
            </span>
            <div class="dropdown-menu dropdown-menu-right">
                {% with instance_full_url="https://www.portalgsti.com.br"|add:instance.get_absolute_url title=instance.title %}
                    {% include 'article/partials/share.html' with title=instance.title url=instance_full_url %}
                {% endwith %}
            </div>
        </div>
    </footer>
</div>