apps/question/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^create/$', views.CreateQuestionView.as_view(), name='create'),
    url(r'^save/$', views.SaveQuestionView.as_view(), name='save'),
    url(r'^edit/(?P<question_id>[0-9]+)$', views.EditQuestionView.as_view(), name='edit'),
    url(r'^update/$', views.UpdateQuestionView.as_view(), name='update'),
    url(r'^show/(?P<question_slug>[a-z0-9]+(?:(-|_)[a-z0-9]+)*)/(?P<question_id>[0-9]+)$', views.ShowQuestionView.as_view(), name='show'),
    url(r'^comment_reply/$', views.CommentReplayView.as_view(), name='comment_reply'),

    url(r'^update_reply/$', views.UpdateReplyView.as_view(), name='update_reply'),

]

rede_gsti/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import cache_page
from apps.core.views.core import Home, CoreAllRanking
from apps.core.views import search as CoreSearch
from apps.core.views.frontend import FrontEndBase
from django.contrib.sitemaps import views as sitemap_views
from apps.core.sitemap import sitemaps
from rede_gsti.urls_old import urls_old
from django.views.generic import RedirectView

handler400 = "apps.core.views.errors.handler400"
handler403 = "apps.core.views.errors.handler403"
handler404 = "apps.core.views.errors.handler404"
handler500 = "apps.core.views.errors.handler500"

url_statics = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
url_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
url_search_all = [url(r'(?P<params>.*)$', CoreSearch.SearchAll.as_view(), name='search_all')]
url_job_vacancy = url(_(r'^jobs/'), include('apps.job_vacancy.urls', namespace='jobs'))

urlpatterns = [

    url(r'^$', Home.as_view(), name='index'),
    url(r'^ranking/$', CoreAllRanking.as_view(), name='ranking'),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(_(r'^admin/'), include(admin.site.urls)),

    # API
    url(r'^api/v(?P<version>(1.0))/', include('apps.api.urls', namespace='api')),

    # Job vacancy
    url_job_vacancy,

    # Translators: URL root de conta
    url(_(r'^account/'), include('apps.core.urls.account', namespace='account')),

    # Translators: URL root de comentario
    url(_(r'^comment/'), include('apps.comment.urls', namespace='comment')),

    # Translators: URL root de pergunta
    url(_(r'^push/'), include('apps.core.urls.push', namespace='push')),

    # Translators: URL root de perfil de usuario
    url(_(r'^profile/'), include('apps.core.urls.user', namespace='profile')),

    # Translators: URL root de company-organization
    url(_(r'^organization/'), include('apps.core.urls.company', namespace='organization')),

    # Translators: URL de conta social
    url(_(r'^socialaccount/'), include('apps.socialaccount.urls', namespace='socialaccount')),

    # Translators: URL de acoes sociais
    url(_(r'^socialactions/'), include('apps.socialactions.urls', namespace='socialactions')),

    # Translators: URL root de redes sociais
    url('', include('social_django.urls', namespace='social')),

    # Translators: URL root de notificacoes
    url(_(r'^notifications/'), include('apps.core.urls.notifications', namespace='notifications')),

    # Translators: URL root de notificacoes
    url(_(r'^hint/'), include('apps.core.urls.hint', namespace='hint')),

    #FIXED ARTICLES REDIRECTS
    url('2011/02/importancia-das-certificacoes.html', RedirectView.as_view(url="/2011/06/importancia-da-certificacao-em-ti-iso.html", permanent=True)),
    url('2012/10/gerenciamento-de-problemas-em-pequenas.html', RedirectView.as_view(url="/2015/11/gerenciamento-de-problemas-em-pequenas-organizacoes.html", permanent=True)),
    url('2013/09/simulado-cobit5.html', RedirectView.as_view(url="/2009/10/simulado-cobit-foundation-5.html", permanent=True)),
    url('2013/02/itil-computacao-em-nuvem.html', RedirectView.as_view(url="/2011/06/computacao-em-nuvem-e-itil-cloud.html", permanent=True)),
    url('2013/02/cloud-computing-foundation.html', RedirectView.as_view(url="/2014/11/itil-e-cloud-computing-video-1724.html", permanent=True)),
    url(r'2012/09/itil-v3-2011.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "itil-v3-2011", 'year': "2012", 'month': '04'}),
    url(r'2011/07/tcc-monografia-em-itil-2.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "tcc-monografia-em-itil-2", 'year': "2012", 'month': '09'}),
    url(r'2009/09/principais-desafios-da-ti-iii.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "principais-desafios-da-ti-ii", 'year': "2009", 'month': '09'}),
    url(r'2016/10/10-passos-para-elaborar-um-plano-da-capacidade-de-ti.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "10-passos-para-elaborar-um-plano-da-capacidade-de-ti", 'year': "2012", 'month': '08'}),
    url(r'2011/07/simulado-iso-27002-foundation-2.html', RedirectView.as_view(pattern_name='article:view', permanent=True), {'slug': "simulado-iso-27002", 'year': "2011", 'month': '04'}),

    # Translators: URL root de publicacao
    url(_(r'^'), include('apps.core.urls.article', namespace='article')),

    # Translators: URL root CORE de acoes sociais
    url(_(r'^'), include('apps.core.urls.socialactions', namespace='core_socialactions')),

    # Translators: URL root de categoria
    url(_(r'^category-feed/'), include('apps.core.urls.category', namespace='category')),

    # Translators: URL root de pergunta
    url(_(r'^question/'), include('apps.core.urls.question', namespace='question')),

    # Translators: URL root de contato
    url(_(r'^contact/'), include('apps.core.urls.contact', namespace='contact')),

    # Translators: URL root de contato
    url(_(r'^mailmanager/'), include('apps.mailmanager.urls', namespace='mailmanager')),

    # Translators: URL root de denuncia
    url(_(r'^complaint/'), include('apps.complaint.urls', namespace='complaint')),

    # Translators: URL root de configuracao
    url(_(r'^settings/'), include('apps.core.urls.configuration', namespace='configuration')),


    # Translators: URL root de fe   ed
    url(_(r'^feed/'), include('apps.core.urls.feed', namespace='feed')),

    # Translators: URL root de amp
    url(_(r'^'), include('apps.core.urls.amp', namespace='amp')),

    # Translators: URL root of user alerts
    url(_(r'^useralerts/'), include('apps.useralerts.urls', namespace='useralerts')),

    # Translators: URL de curso
    url(_(r'^courses/'), include('apps.core.urls.course', namespace='course')),

    # Translators: URL de curso
    url(_(r'^rating/'), include('apps.core.urls.rating', namespace='rating')),

    # Translators: URL core adicionais
    url(_(r'^'), include('apps.core.urls.core', namespace='core')),

    url(r'^chaining/', include('smart_selects.urls')),

    # Translators: URL de buscai
    url(_(r'^'), include('apps.core.urls.search', namespace='search')),



    # Translators: URl geography
    url(_(r'^geography/'), include('apps.core.urls.geography', namespace='geography')),


    url(_(r'^superadmin/'), include('apps.core.urls.superuser', namespace='superuser')),

    # Translators: URL root de comunidade
    url(_(r'^'), include('apps.core.urls.community', namespace='community')),

    url(r'^ideia-summernote/', include('apps.core.urls.summernote', namespace='ideia-summernote')),

    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', cache_page(settings.TIME_TO_REFRESH_SITEMAP)(sitemap_views.sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url(r'^', include('apps.core.urls.blogspot', namespace='blogspot')),

] + url_statics + url_media + urls_old
urls_front_end = [
    url(_(r'^front-end/(?P<template>[a-z0-9./]+(?:(-|_)[a-z0-9.]+)*)'), FrontEndBase.as_view())
]

if not (settings.ENVIRONMENT=='production'):
    urlpatterns += urls_front_end

if hasattr(settings, 'PROFILER_APP') and getattr(settings, 'PROFILER_APP') == 'silk' and getattr(settings, 'ENVIRONMENT') == 'develop':
    urlpatterns += [
        url(r'^admin/silk/', include('silk.urls', namespace='silk'))
    ]
# urlpatterns += url_search_all

templates/home/categorias/banco-de-dados.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='databases' %}

templates/home/categorias/community-list.html
{% if feed_objects %}
    {% for feed in feed_objects %}


        {% with template_name=feed.content_type|stringformat:"s"|add:"-segment.html" %}
            {% with instance=feed.content_object %}
                {% if instance %}
                    {% include 'userprofile/partials/'|add:template_name %}
                {% endif %}
            {% endwith %}
        {% endwith %}
    {% endfor %}

    {% if feed_objects.has_next %}
        <a data-jscroll-next href="{% url 'category:show' category_slug %}?&page={{ page }}">Próximo</a>
    {% endif %}

{% else %}
    <hr/>

{% endif %}

templates/home/categorias/default.html
{% extends 'home/layout/base.html'%}
{% load social_tags %}
{% load home_blocks %}
{% load article_blocks %}
{% load home_cache %}
{% load category_tags %}
{% load cache %}
{% load thumbor_tags %}
{% load bighomecache %}
{% load user_agents %}
{% load ads %}
{% load abs_url %}
{% load seo_pagination_tags %}
{% load static_versioned %}
{% load home %}
{% block seo-og-title %}{% block seo_title %}{{ category.description }} {{ block.super }}{% endblock %}{% endblock %}
{% block seo-og-description %}{% block seo-description %}Saiba tudo sobre {{ category.description }} através dessa categoria do site. Aqui está reunido o conteúdo criado por colaboradores do Portal sobre esse assunto.{% endblock %}{% endblock %}
{% block seo-og-image %}{% thumbor_url category.community_related.get_picture.url width=82 height=82 smart=False fit_in=False %}{% endblock %}

{% block seo-canonical %}{% absolute_url request.get_full_path %}{% endblock %}
{% block link_pagination %}
    {% pagination_links feed_objects %}
{% endblock link_pagination %}

{% block page_stylesheet %}
<link rel="stylesheet" href="//unpkg.com/slick-carousel@1.8.1/slick/slick.css">
<link rel="stylesheet" href="//unpkg.com/slick-carousel@1.8.1/slick/slick-theme.css">
<link rel="stylesheet" href="{% static_versioned 'stylesheets/category.css' %}">
{% endblock page_stylesheet %}

{% with class_name=class_name|default_if_none:"default" %}

    {% block content %}
    <main class="app-main page-category">
        <div class="page-category-banner">
            {% ads_only_production "category_top" "all" %}
        </div>
        <div class="page-category-container">
            <h1 class="page-category-title">
                <span class="{{ class_name }}">{{ category.description }}</span>
            </h1>
        </div>
        <div class="page-category-container">
            {% article_section_large category_slug feed_articles_list 3 class_name %}
            {% with community=category.community_related %}
                {% include "userprofile/partials/profile-card-community.html" with community_obj=community class_name=class_name %}
            {% endwith %}
        </div>
        <div class="page-category-container">
            {% article_section_large category_slug feed_articles_list 4 class_name %}
        </div>
        <div class="page-category-container">
            {% article_section_large category_slug feed_articles_list 4 class_name %}
        </div>
        <div class="page-category-container">    
            {% article_section_large category_slug feed_articles_list 4 class_name %}
        </div>
    {% with key=category.slug|add:"_communities" %}

            {% communities_slider category 3600 %}

    {% endwith %}

        <div class="page-category-container page-category-content-after">
            <div class="page-category-latests">
                <h2 class="page-category-subtitle">
                    <span class="{{ class_name }}">Últimas</span>
                </h2>
                <div class="page-category-posts">
                    {% article_section_large category_slug feed_articles_list 3 class_name %}
                </div>
                <div class="page-category-posts">
                    {% article_section_large category_slug feed_articles_list 3 class_name %}
                </div>
                <div class="page-category-posts">
                    {% article_section_large category_slug feed_articles_list 3 class_name %}
                </div>
                <div class="page-category-posts">
                    {% article_section_large category_slug feed_articles_list 3 class_name %}
                </div>
            </div>
            <div class="page-category-aside">
                {% cache 3600 "category-sidebar-right" %}
                    {% last_courses 5 %}
                    {% video_section 2 %}
                {% endcache %}

            </div>
        </div>
    </main>
    {% endblock %}

    {% block javascripts %}
        <div id="fb-root"></div>
        <script src="//unpkg.com/slick-carousel@1.8.1/slick/slick.min.js"></script>
        <script type="text/javascript">
            $(function() {
                $(".j-scroll-communities").jscroll({
                    contentSelect: ".j-scroll-communities-container",
                    loadingHtml: '<div class="load-async-preload"></div>',
                    nextSelector: "a[data-jscroll-next]",
                    callback: function (data) {
                        refreshAsyncLike();
                    }
                });
                var $social_count = $("[data-social-count=\"true\"]");
                $.each($social_count, function(key, value){
                    var $obj = $(value);
                    $.get($obj.data("url"), function(data){
                        $obj.text(data.count);
                    });
                });
                $('[data-toggle="carousel"]').slick({
                    centerMode: true,
                    dots: false,
                    infinite: true,
                    prevArrow: "<button type='button' class='slick-prev communities-slider-arrow'><i class='gsticon gsticon-angle-left' aria-hidden='true'></i></button>",
                    nextArrow: "<button type='button' class='slick-next communities-slider-arrow'><i class='gsticon gsticon-angle-right' aria-hidden='true'></i></button>",
                    speed: 500,
                    variableWidth: true,
                    slidesToShow: 8,
                    slidesToScroll: 1,
                    responsive: [{
                        breakpoint: 769,
                        settings: {
                            arrows: false,
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            arrows: false,
                            slidesToScroll: 2,
                        }
                    }]
                });
            });
        </script>
    {% endblock %}
{% endwith %}

templates/home/categorias/desenvolvimento.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='development' %}

templates/home/categorias/design.html
{% include 'home/categorias/default.html' with class_name='design' %}

templates/home/categorias/governanca-de-ti.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='governance' %}

templates/home/categorias/governanca-e-gestao.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='governance' %}

templates/home/categorias/infraestrutura.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='infra' %}

templates/home/categorias/mais.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='more' %}

templates/home/categorias/marketing-digital.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='marketing' %}

templates/home/categorias/mobile.html
{# TODO Pensar em forma melhor e dinâmica #}
{% include 'home/categorias/default.html' with class_name='mobile' %}

templates/home/categorias/web-design.html
{% include 'home/categorias/default.html' with class_name='design' %}